/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;
import java.awt.Rectangle;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Admin
 */
public class t extends javax.swing.JFrame {

    /**
     * Creates new form t
     */
    public t() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr = new javax.swing.JScrollPane();
        pan = new javax.swing.JPanel();
        text = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scr.setHorizontalScrollBar(null);
        scr.setVerticalScrollBar(new combo_suggestion.ScrollBarCustom());

        pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        scr.setViewportView(pan);

        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });

        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(text)))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scr, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        //Tao label
        String t = text.getText();
        com.k33ptoo.components.KGradientPanel cbox = new com.k33ptoo.components.KGradientPanel();
        javax.swing.JTextArea txt = new javax.swing.JTextArea();
        txt.setText(t);
        
        int num = 0;
        for(int i = 0; i < t.length() ; i++){ if(t.charAt(i) == 'w' || t.charAt(i) == 'm'){num++;} }
        width = t.length()*8+(t.matches("[A-Z]{1,}") ? 12 : (t.contains("m") || t.contains("w") ? 10*num : 8));
        line = width < 300 ? 1 : (width/300);
        X = width < 300 ? 300 - width + 50 : 50;
        Y = Y + preHeight + 20;
        preHeight = (line*22) + (line > 1 ? 20 : 0);
        
        cbox.setkBorderRadius(20);
        cbox.setkEndColor(new java.awt.Color(241, 135, 251));
        cbox.setkGradientFocus(180);
        cbox.setkStartColor(new java.awt.Color(67, 156, 251));
        

        txt.setBackground(new Color(0,0,0,0));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt.setLineWrap(true);
        txt.setRows(1000);
        txt.setWrapStyleWord(true);
        txt.setBorder(null);
        
        javax.swing.GroupLayout cboxLayout = new javax.swing.GroupLayout(cbox);
        cbox.setLayout(cboxLayout);
        cboxLayout.setHorizontalGroup(
            cboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, width < 300 ? width : 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        cboxLayout.setVerticalGroup(
            cboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        //pack();
        setLocationRelativeTo(null);
        
        //gan label vao panel
        pan.add(cbox, new AbsoluteConstraints(X, Y, -1, -1));// 0, i*20 la toa do, 370, 40 là kich thuoc
        //focus theo label khi label dài xuong
        Rectangle aRect = new Rectangle();
        aRect.y = Y + 50;
        pan.scrollRectToVisible(aRect);
        validate();
        repaint();
        text.setText("");
    }//GEN-LAST:event_textActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        String t = text1.getText();
        com.k33ptoo.components.KGradientPanel cbox = new com.k33ptoo.components.KGradientPanel();
        javax.swing.JTextArea txt = new javax.swing.JTextArea();
        txt.setText(t);
        int num = 0;
        for(int i = 0; i < t.length() ; i++){ if(t.charAt(i) == 'w' || t.charAt(i) == 'm'){num++;} }
        width = t.length()*8+(t.matches("[A-Z]{1,}") ? 12 : (t.contains("m") || t.contains("w") ? 10*num : 8));
        line = width < 300 ? 1 : (width/300);
        X = 20;
        Y = Y + preHeight + 20;
        preHeight = (line*22) + (line > 1 ? 20 : 0);
        
        cbox.setkBorderRadius(20);
        cbox.setkEndColor(new java.awt.Color(150, 198, 234));
        cbox.setkGradientFocus(250);
        cbox.setkStartColor(new java.awt.Color(181, 151, 246));
        
        txt.setBackground(new Color(0,0,0,0));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt.setLineWrap(true);
        txt.setRows(1000);
        txt.setWrapStyleWord(true);
        txt.setBorder(null);

        javax.swing.GroupLayout cboxLayout = new javax.swing.GroupLayout(cbox);
        cbox.setLayout(cboxLayout);
        cboxLayout.setHorizontalGroup(
            cboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, width < 300 ? width : 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        cboxLayout.setVerticalGroup(
            cboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        setLocationRelativeTo(null);
        
        //gan label vao panel
        pan.add(cbox, new AbsoluteConstraints(X, Y, -1, -1));// 0, i*20 la toa do, 370, 40 là kich thuoc
        //focus theo label khi label dài xuong
        Rectangle aRect = new Rectangle();
        aRect.y = Y + 50;
        pan.scrollRectToVisible(aRect);
        validate();
        repaint();
        text1.setText("");
    }//GEN-LAST:event_text1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(t.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(t.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(t.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(t.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new t().setVisible(true);
            }
        });
    }
    int preHeight = 0, width, line, X, Y;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pan;
    private javax.swing.JScrollPane scr;
    private javax.swing.JTextField text;
    private javax.swing.JTextField text1;
    // End of variables declaration//GEN-END:variables

    
}